### ISSUE TITLE
https://www.dropbox.com/scl/fi/4hokrar8ujhb05y0fd6rq/electricity-understand-and-be-safe-2019.pdf?rlkey=wwwem5la0bbbho5t1qdci62aq&dl=0

### ISSUE THREAD

**Issue by nxdf** [sigalor/borderland.pro#3]
Please replace the "electricity guide" link with this one
https://www.dropbox.com/scl/fi/4hokrar8ujhb05y0fd6rq/electricity-understand-and-be-safe-2019.pdf?rlkey=wwwem5la0bbbho5t1qdci62aq&dl=0

The current one requires permissions. The one I give above is public

**Comment by sigalor** [comment]
Awesome, thanks so much, fixed it!
